I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1044, in script
    c "We are open to feedback and suggestions.  You can get a hold of us at {a=amethystgeoadventure@gmail.com}amethystgeoadventure@gmail.com{/a}"
  File "renpy/common/00defaults.rpy", line 197, in hyperlink_function
    return config.hyperlink_handlers[protocol](value)
  File "renpy/common/00defaults.rpy", line 161, in call_in_new_context_handler
    renpy.call_in_new_context(value)
ScriptError: could not find label 'amethystgeoadventure@gmail.com'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1044, in script
    c "We are open to feedback and suggestions.  You can get a hold of us at {a=amethystgeoadventure@gmail.com}amethystgeoadventure@gmail.com{/a}"
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\character.py", line 1142, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\character.py", line 842, in do_display
    **display_args)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\character.py", line 591, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 3518, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\screen.py", line 714, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\layout.py", line 244, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\text\text.py", line 1924, in event
    rv = self.style.hyperlink_functions[1](target)
  File "renpy/common/00defaults.rpy", line 197, in hyperlink_function
    return config.hyperlink_handlers[protocol](value)
  File "renpy/common/00defaults.rpy", line 161, in call_in_new_context_handler
    renpy.call_in_new_context(value)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\game.py", line 332, in call_in_new_context
    return renpy.execution.run_context(False)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'amethystgeoadventure@gmail.com'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
GeoAdventures 1.0
Sat May 30 13:09:33 2020
