I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    e "Ingeous rocks are formed by melting existing rocks deep underground\n
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 60, in script
    e "Ingeous rocks are formed by melting existing rocks deep underground\n
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'e' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Geology 1.0
Wed May 13 15:26:06 2020
